// orders.js

const Orders = [
  {
    ID: 0,
    clientName: "Hatim",
    productName: "pizza",
    productNumber: "2321",
    paymentStatus: "Paid",
    shipping: "Deliverd",
  },
  {
    ID: 1,
    clientName: "Ahmed",
    productName: "water",
    productNumber: "8713",
    paymentStatus: "Paid",
    shipping: "Pending",
  },
  {
    ID: 2,
    clientName: "Hajar",
    productName: "Coca-cola",
    productNumber: "3765",
    paymentStatus: "Due",
    shipping: "Deliverd",
  },
  {
    ID: 3,
    clientName: "Douae",
    productName: "Milk",
    productNumber: "5343",
    paymentStatus: "Paid",
    shipping: "Deliverd",
  },
  {
    ID: 4,
    clientName: "Douae",
    productName: "Milk",
    productNumber: "5343",
    paymentStatus: "Paid",
    shipping: "Deliverd",
  },
  {
    ID: 5,
    clientName: "Douae",
    productName: "Milk",
    productNumber: "5343",
    paymentStatus: "Paid",
    shipping: "Deliverd",
  },
  {
    ID: 6,
    clientName: "Douae",
    productName: "Milk",
    productNumber: "5343",
    paymentStatus: "Paid",
    shipping: "Deliverd",
  },
  {
    ID: 7,
    clientName: "Douae",
    productName: "Milk",
    productNumber: "5343",
    paymentStatus: "Paid",
    shipping: "Deliverd",
  },
  {
    ID: 8,
    clientName: "Douae",
    productName: "Milk",
    productNumber: "5343",
    paymentStatus: "Paid",
    shipping: "Deliverd",
  },
  {
    ID: 9,
    clientName: "Douae",
    productName: "Milk",
    productNumber: "5343",
    paymentStatus: "Paid",
    shipping: "Deliverd",
  },
  {
    ID: 10,
    clientName: "Douae",
    productName: "Milk",
    productNumber: "5343",
    paymentStatus: "Paid",
    shipping: "Deliverd",
  },
  {
    ID: 11,
    clientName: "Douae",
    productName: "Milk",
    productNumber: "5343",
    paymentStatus: "Paid",
    shipping: "Deliverd",
  },
  {
    ID: 12,
    clientName: "Douae",
    productName: "Milk",
    productNumber: "5343",
    paymentStatus: "Paid",
    shipping: "Deliverd",
  },
  {
    ID: 13,
    clientName: "Douae",
    productName: "Milk",
    productNumber: "5343",
    paymentStatus: "Paid",
    shipping: "Deliverd",
  },
  {
    ID: 14,
    clientName: "Douae",
    productName: "Milk",
    productNumber: "5343",
    paymentStatus: "Paid",
    shipping: "Deliverd",
  },
  {
    ID: 15,
    clientName: "Douae",
    productName: "Milk",
    productNumber: "5343",
    paymentStatus: "Paid",
    shipping: "Deliverd",
  },
];
